pull bouton
2PING2/PING2 pull request #4
Opened 2024-12-19 14:45 UTC by thomasraffray

2024-12-25 08:25 UTC, robinAZERTY commented
Même commentaires que dans [ton autre pull request](https://github.com/2PING2/PING2/pull/5), à savoir :
- mettre à jour le ```gitignore```
- inclure le fichier ```LICENCE```
- inclure le fichier ```README.md```
- traduire ton code (et commentaires) en anglais

N'oublie pas de bien décrire la manette qui est programmées dans les ```README.md```. Ou même de faire un petit dossier ```/doc```avec des photos si tu es motivé. Cela pourrait aider à faire la différence entre les deux branches.

Ton code constitura la première version de la branche [hardware/gameController3buttons](https://github.com/2PING2/PING2/tree/hardware/gameController3buttons).

2024-12-26 09:22 UTC, robinAZERTY requested changes
Merci d'effectuer les changements pour que je puisse merger.

2025-01-06 13:04 UTC, robinAZERTY submitted a review, later dismissed
Parfait

2025-01-06 13:04 UTC, robinAZERTY commented on src/main.cpp
Ok pour les conventions d'écriture. Il ne reste plus que le ```readme.md``` à mettre à jour.

2025-01-06 13:07 UTC, thomasraffray commented on src/main.cpp
c'est résolu

2025-01-06 13:34 UTC, merged