Manette joystick
2PING2/PING2 pull request #5
Opened 2024-12-19 14:46 UTC by thomasraffray

2024-12-25 08:08 UTC, robinAZERTY commented
C'est top, merci d'avoir ouvert ce pull request. Une fois les changements effectués, ton code constitura la première version de la nouvelle branche des manettes.

2024-12-26 09:20 UTC, robinAZERTY requested changes
Merci d'effectuer les changement pour que je puisse merger.

2025-01-06 13:45 UTC, thomasraffray commented on src/main.cpp
done

2025-01-06 13:52 UTC, robinAZERTY approved these changes

2025-01-06 13:52 UTC, merged